name: show-me-tasks-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DB_URL: "jdbc:h2:mem:testdb"
        DB_USERNAME: "sa"
        DB_PASSWORD: "password"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle Wrapper
        working-directory: to-do-app/BackEnd
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: to-do-app/BackEnd
        run: ./gradlew build --no-daemon

      - name: Run Tests
        working-directory: to-do-app/BackEnd
        run: |
          ./gradlew clean test --no-daemon -Dspring.profiles.active=test
          cat build/reports/tests/test/index.html

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: to-do-app/BackEnd/build/reports/tests/test